// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "RakutenDemo",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "RakutenDemo",
            targets: ["RakutenDemo"],
            bundleIdentifier: "yossibank-yahoo.co.jp.RakutenDemo",
            teamIdentifier: "6WHPY5MQSB",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .magicWand),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "../../Package")
    ],
    targets: [
        .executableTarget(
            name: "RakutenDemo",
            dependencies: [
                .product(
                    name: "RakutenView",
                    package: "Package"
                )
            ],
            path: "Sources",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.v6]
)
